name: coastwatch
channels:
  - conda-forge
dependencies:
# Not all packages will be available from conda-forge, we install from pip when we need to.
  - pip
  - pip:
    # Access linux desktop from inside JupyterHub
    - jupyter-remote-desktop-proxy
