#!/bin/bash
set -e

cd /tmp
wget https://www.star.nesdis.noaa.gov/socd/coastwatch/cwf/cwutils-4_0_0_198-linux-x86_64.tar.gz
tar -zxf cwutils-4_0_0_198-linux-x86_64.tar.gz
rm -rf cwutils-4_0_0_198-linux-x86_64.tar.gz

export PATH=${PATH}:/tmp/cwutils-4.0.0.198/bin
export MANPATH=${MANPATH}:/tmp/cwutils_4.0.0.198/doc/man
export INSTALL4J ADD VM PARAMS=-Dsun.java2d.uiScale=2.0
